- :file: 1.html
  :desc: Seasonal product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=122408
  :method: :get
  :query_params:
    :id: 122408
  :expectation:
    :id: 122408
    :name: Pascual Toso Malbec Rose
    :tags: ["pascual", "toso", "malbec", "rose", "wine", "argentina", "bottle"]
    :price_in_cents: 1195
    :regular_price_in_cents: 1195
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :alcohol_content: 1270
    :price_per_liter_of_alcohol_in_cents: 1254
    :price_per_liter_in_cents: 1593
    :sugar_content: "1"
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :origin: Argentina
    :producer_name: Pascual Toso
    :released_on:
    :stock_type: LCBO
    :primary_category: Wine
    :secondary_category:
    :is_vqa: false
    :is_kosher: false
    :has_bonus_reward_miles: false
    :has_limited_time_offer: false
    :is_discontinued: false
    :is_seasonal: true
    :description:
    :tasting_note:
    :serving_suggestion:

- :file: 2.html
  :desc: Product with limited time offer
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=18
  :method: :get
  :query_params:
    :id: 18
  :expectation:
    :id: 18
    :name: Heineken Lager
    :tags: ["heineken", "lager", "beer", "netherlands", "heinekens", "brouwerijen", "nederland", "bv", "bottle"]
    :price_in_cents: 1250
    :regular_price_in_cents: 1350
    :limited_time_offer_savings_in_cents: 100
    :limited_time_offer_ends_on: 2010-08-15
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :alcohol_content: 500
    :price_per_liter_of_alcohol_in_cents: 1262
    :price_per_liter_in_cents: 631
    :sugar_content: "7"
    :package: 6x330 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 330
    :total_package_units: 6
    :total_package_volume_in_milliliters: 1980
    :origin: Netherlands
    :producer_name: Heineken's Brouwerijen Nederland Bv
    :released_on:
    :stock_type: LCBO
    :primary_category: Beer
    :secondary_category: Lager
    :has_bonus_reward_miles: false
    :has_limited_time_offer: true
    :is_vqa: false
    :is_kosher: false
    :is_discontinued: false
    :is_seasonal: false
    :description:
    :tasting_note: "Pale gold colour; softly perfumed nose with some hoppy elements; soft grain taste; gently bitter finish."
    :serving_suggestion: "Medium curry, pizza or burgers"

- :file: 3.html
  :desc: Product with bonus air miles
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=280461
  :method: :get
  :query_params:
    :id: 280461
  :expectation:
    :id: 280461
    :name: Dom Pérignon Brut Champagne
    :tags: ["dom", "pérignon", "brut", "champagne", "wine", "france", "moet", "chandon", "sa", "bottle", "perignon"]
    :price_in_cents: 21995
    :regular_price_in_cents: 21995
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 30
    :bonus_reward_miles_ends_on: 2010-08-14
    :alcohol_content: 1250
    :price_per_liter_of_alcohol_in_cents: 23461
    :price_per_liter_in_cents: 29326
    :sugar_content: XD
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :origin: Champagne, France
    :producer_name: Moet & Chandon S.A.
    :released_on: 2010-05-15
    :stock_type: VINTAGES
    :primary_category: Wine
    :secondary_category: Champagne
    :has_bonus_reward_miles: true
    :has_limited_time_offer: false
    :is_vqa: false
    :is_kosher: false
    :is_discontinued: false
    :is_seasonal: false
    :description: "The legend now joins our Essentials Collection. Purported to be the father of all Champagne, Dom Pérignon continues to impress generation after generation. This ultimate anniversary, or birthday celebration, bubbly is only made in the greatest years. Loaded with stylish aromas of citrus, artisanal bread, green apple, mineral and pear, it's quite dry and vibrantly refreshing on the palate. Every vintage Robert Parker has reviewed from 1982 to the present has received scores in the range of 92 to 98 points! Expect to be impressed."
    :tasting_note:
    :serving_suggestion:

- :file: 4.html
  :desc: Discontinued product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=479154
  :method: :get
  :query_params:
    :id: 479154
  :expectation:
    :id: 479154
    :name: Floris Ninkeberry Gardenbeer
    :tags: ["floris", "ninkeberry", "gardenbeer", "beer", "ale", "belgium", "brouwerij", "huyghe", "bottle"]
    :price_in_cents: 250
    :regular_price_in_cents: 250
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :alcohol_content: 350
    :price_per_liter_of_alcohol_in_cents: 2164
    :price_per_liter_in_cents: 757
    :sugar_content: "8"
    :package: 330 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 330
    :total_package_units: 1
    :total_package_volume_in_milliliters: 330
    :origin: Belgium
    :producer_name: Brouwerij Huyghe
    :released_on:
    :stock_type: LCBO
    :primary_category: Beer
    :secondary_category: Ale
    :has_bonus_reward_miles: false
    :has_limited_time_offer: false
    :is_vqa: false
    :is_kosher: false
    :is_discontinued: true
    :is_seasonal: false
    :description:
    :tasting_note:
    :serving_suggestion:

- :file: 5.html
  :desc: Product with release date
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=148528
  :method: :get
  :query_params:
    :id: 148528
  :expectation:
    :id: 148528
    :name: Bodegas Ruconia Rey Don Garcia El de Najera Crianza 2005
    :tags: ["bodegas", "ruconia", "rey", "don", "garcia", "el", "de", "najera", "crianza", "2005", "wine", "red", "rioja", "spain", "sl", "bottle"]
    :price_in_cents: 1595
    :regular_price_in_cents: 1595
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :alcohol_content: 1320
    :price_per_liter_of_alcohol_in_cents: 1611
    :price_per_liter_in_cents: 2126
    :sugar_content: "XD"
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :origin: Rioja, Spain
    :producer_name: Bodegas Ruconia S.L.
    :released_on: 2010-01-23
    :stock_type: VINTAGES
    :primary_category: Wine
    :secondary_category: Red Wine
    :has_bonus_reward_miles: false
    :has_limited_time_offer: false
    :is_vqa: false
    :is_kosher: false
    :is_discontinued: false
    :is_seasonal: false
    :description:
    :tasting_note: "Excellent example of a more mature Crianza, featuring aromas of cherry, dried fruit, vanilla and sweet oak spice. Dry and fruity, this wine's tannins have softened out considerably making this wine very approachable. A fine wine for a rich lamb stew or roast beef. (VINTAGES panel, July 2009)"
    :serving_suggestion:

- :file: 6.html
  :desc: Standard product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=582973
  :method: :get
  :query_params:
    :id: 582973
  :expectation:
    :id: 582973
    :name: Bombay Sapphire
    :tags: ["bombay", "sapphire", "spirits", "gin", "england", "united", "kingdom", "company", "ltd", "bottle"]
    :price_in_cents: 5545
    :regular_price_in_cents: 5545
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :alcohol_content: 4000
    :price_per_liter_of_alcohol_in_cents: 792
    :price_per_liter_in_cents: 3168
    :sugar_content:
    :package: 1750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 1750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 1750
    :origin: England, United Kingdom
    :producer_name: Bombay Spirits Company Ltd.
    :released_on:
    :stock_type: LCBO
    :primary_category: Spirits
    :secondary_category: Gin
    :has_bonus_reward_miles: false
    :has_limited_time_offer: false
    :is_vqa: false
    :is_kosher: false
    :is_discontinued: false
    :is_seasonal: false
    :description:
    :tasting_note: "Clear water white; complex mix of herbs and juniper on the nose with crisp lemon peel flavours; smooth and refreshing"
    :serving_suggestion: "Martinis, mixed drinks"

- :file: 7.html
  :desc: VQA product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=2183079
  :method: :get
  :query_params:
    :id: 2183079
  :expectation:
    :id: 2183079
    :name: Lake & River Series Cabernet Franc VQA
    :tags: ["lake", "river", "series", "cabernet", "franc", "vqa", "wine", "ontario", "canada", "colio", "wines", "of", "ltd", "bottle"]
    :price_in_cents: 1095
    :regular_price_in_cents: 1095
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :alcohol_content: 1220
    :price_per_liter_of_alcohol_in_cents: 1196
    :price_per_liter_in_cents: 1460
    :sugar_content:
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :origin: Ontario, Canada
    :producer_name: Colio Wines of Canada Ltd.
    :released_on:
    :stock_type: LCBO
    :primary_category: Wine
    :secondary_category:
    :has_bonus_reward_miles: false
    :has_limited_time_offer: false
    :is_vqa: true
    :is_kosher: false
    :is_discontinued: false
    :is_seasonal: false
    :description:
    :tasting_note:
    :serving_suggestion:

- :file: 8.html
  :desc: Kosher Product
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=114173
  :method: :get
  :query_params:
    :id: 114173
  :expectation:
    :id: 114173
    :name: 05 Sauv Blanc Weinstock Cellar K
    :tags: ["05", "sauv", "blanc", "weinstock", "cellar", "k", "wine", "california", "united", "states", "royal", "wines", "bottle"]
    :price_in_cents: 2295
    :regular_price_in_cents: 2295
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: VINTAGES
    :primary_category: Wine
    :secondary_category:
    :origin: California, United States
    :package: 750 mL bottle
    :package_unit_type: bottle
    :package_unit_volume_in_milliliters: 750
    :total_package_units: 1
    :total_package_volume_in_milliliters: 750
    :volume_in_milliliters: 750
    :alcohol_content: 1350
    :price_per_liter_of_alcohol_in_cents: 2266
    :price_per_liter_in_cents: 3060
    :sugar_content:
    :producer_name: Royal Wines
    :released_on:
    :is_discontinued: false
    :has_limited_time_offer: false
    :has_bonus_reward_miles: false
    :is_seasonal: false
    :is_vqa: false
    :is_kosher: true
    :description:
    :serving_suggestion:
    :tasting_note:

- :file: 9.html
  :desc: Product with Value Added Promotion
  :uri: http://lcbo.com/lcbo-ear/lcbo/product/details.do?language=EN&itemNumber=56796
  :method: :get
  :query_params:
    :id: 56796
  :expectation:
    :id: 56796
    :name: Heineken Draught Keg
    :tags: ["heineken", "draught", "keg", "beer", "lager", "netherlands", "heinekens", "brouwerijen", "nederland", "bv", "can"]
    :price_in_cents: 2995
    :regular_price_in_cents: 2995
    :limited_time_offer_savings_in_cents: 0
    :limited_time_offer_ends_on:
    :bonus_reward_miles: 0
    :bonus_reward_miles_ends_on:
    :stock_type: LCBO
    :primary_category: Beer
    :secondary_category: Lager
    :origin: Netherlands
    :package: 5000 mL can
    :package_unit_type: can
    :package_unit_volume_in_milliliters: 5000
    :total_package_units: 1
    :total_package_volume_in_milliliters: 5000
    :volume_in_milliliters: 5000
    :alcohol_content: 500
    :price_per_liter_of_alcohol_in_cents: 1198
    :price_per_liter_in_cents: 599
    :sugar_content: "3"
    :producer_name: Heineken's Brouwerijen Nederland Bv
    :released_on:
    :is_discontinued: false
    :has_limited_time_offer: false
    :has_bonus_reward_miles: false
    :has_value_added_promotion: true
    :is_seasonal: false
    :is_vqa: false
    :is_kosher: false
    :description:
    :serving_suggestion: Medium curry, pizza or burgers
    :tasting_note: Pale gold colour; softly perfumed nose with some hoppy elements; soft grain taste; gently bitter finish.
    :value_added_promotion_description: 5000 mL can comes with FREE Cooler Bag Wrap until Jan 1, 2011 or while supplies last!
